---
# ClusterRole for KServe access
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubeflow-kserve-access
rules:
- apiGroups:
  - serving.kserve.io
  resources:
  - inferenceservices
  verbs:
  - get
  - list
  - create
  - update
  - patch
  - delete
- apiGroups:
  - serving.knative.dev
  resources:
  - services
  verbs:
  - get
  - list

---
# ClusterRoleBinding for pipeline-runner
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubeflow-pipeline-runner-kserve
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubeflow-kserve-access
subjects:
- kind: ServiceAccount
  name: pipeline-runner
  namespace: kubeflow

---
# Additional ClusterRoleBinding for default namespace
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kubeflow-pipeline-runner-kserve-default
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubeflow-kserve-access
subjects:
- kind: ServiceAccount
  name: pipeline-runner
  namespace: kubeflow
